CREATE OR REPLACE PACKAGE TEST_RUNNER_REPO.TABLECOPY_PACKAGE AS
    FUNCTION TABLE_EXISTS(
        p_TABLE_OWNER VARCHAR2,
        p_TABLE_NAME VARCHAR2
    ) RETURN BOOLEAN;

PROCEDURE TABLECOPY (
    p_source_schema VARCHAR2,
    p_source_table VARCHAR2,
    p_target_schema VARCHAR2,
    p_target_table VARCHAR2,
    p_truncate BOOLEAN DEFAULT FALSE,
    p_tnd_filter DATE DEFAULT NULL
);
END TABLECOPY_PACKAGE;
/
