CREATE OR REPLACE PACKAGE TEST_RUNNER_REPO.TEST_PACKAGE IS
  v_error VARCHAR2(4000);
  v_start_time TIMESTAMP(6);
  v_end_time TIMESTAMP(6);
  v_output VARCHAR2(4000);
  v_schstatus VARCHAR2(4000);

  FUNCTION TEST_RUNNER(v_id IN TESTS.ID%TYPE) RETURN NUMBER;
  PROCEDURE RUN_TEST(v_id IN TESTS.ID%TYPE, V_RUN_ID IN NUMBER);
END TEST_PACKAGE;
/
