name: Test runner dev deploy
on: workflow_dispatch

jobs:
  dev-deploy:
    if: contains(fromJSON('["IHUASART", "IHUAMOAK", "IHUAA10L"]'), github.triggering_actor)
    runs-on: [self-hosted, rbhu-dpd-test-runner]
    env:
      SSH_KEY: ${{ secrets.TEST_RUNNER_DEV_PRIV_KEY_PATH }}
      SSH_USER: ${{ secrets.TEST_RUNNER_DEV_USERNAME }}
      SSH_HOST: ${{ secrets.TEST_RUNNER_DEV_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: raiffeisen/rbhu-ods-test-runner
          ref: main
          token: ${{ secrets.CHECKOUT_TOKEN }}
          path: rbhu-ods-test-runner
      - name: Deploy changes 
        run: |
          echo "Copy files"
          scp -i $SSH_KEY -r ${{ github.workspace }}/rbhu-ods-test-runner/* $SSH_USER@$SSH_HOST:/srv/www/ods_test_runner/rbhu-ods-test-runner/
      - name: Restart gunicorn
        run:  |
          echo  "Restart guinicorn"
          ssh -i $SSH_KEY -t $SSH_USER@$SSH_HOST 'sudo systemctl restart gunicorn_otr.service'
